import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MaintenanceGate from "@/components/MaintenanceGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Resolved at build time. NEXT_PUBLIC_SITE_URL takes precedence (set this
// in Vercel for the live origin); otherwise we fall back to localhost so
// dev builds still satisfy Next 16's metadata-resolution requirement and
// stop spamming the "metadataBase property … not set" warning on every
// page render. Without metadataBase, OG/Twitter image URLs in the metadata
// below would resolve relative to nothing and Next falls back to
// localhost anyway — making the env-var explicit just silences the warning
// and gives us correct social-card images on prod.
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  // `template` lets nested routes (e.g. /admin) override just the leaf
  // and still get the "AcademiCats · Admin" suffix shape. `default` is
  // what shows on the bare landing.
  title: {
    default:  "AcademiCats",
    template: "%s · AcademiCats",
  },
  description: "From research to writing — in minutes, not days.",
  // OpenGraph / Twitter card meta. The actual images are generated by
  // app/opengraph-image.tsx + app/twitter-image.tsx (dynamic 1200×630
  // banners via next/og ImageResponse) — Next auto-injects the
  // og:image / twitter:image tags pointing at them, so we DON'T list
  // images here (manual + file-convention would emit two competing
  // tags and the recipient's social card preview becomes a coin flip).
  openGraph: {
    title:       "AcademiCats",
    description: "From research to writing — in minutes, not days.",
    type:        "website",
    siteName:    "AcademiCats",
  },
  twitter: {
    // summary_large_image renders the full 1200×630 banner inline with
    // the link, instead of the tiny avatar-style thumbnail `summary`
    // produces. CTR on shared links typically jumps 2-3× for the same
    // copy when the card upgrades to the large format.
    card:        "summary_large_image",
    title:       "AcademiCats",
    description: "From research to writing — in minutes, not days.",
  },
  // Tells Next to honour the public/robots.txt we ship rather than the
  // framework default (no robots directive). The policy lives in
  // public/robots.txt — see comments there.
  robots: { index: true, follow: true },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Page-level translation is re-enabled — Google Translate can freely translate
  // the whole app, including the Research Brief (previously gated because we
  // worried the streaming markdown diff would collide with Google's DOM
  // rewrite, which turned out not to happen in practice). A few remaining
  // volatile regions (textarea overlay, Lab result, history timeline, agent
  // logs) still opt out individually via `translate="no"` + `notranslate`
  // because their mid-render DOM churn IS sensitive to external rewrites —
  // the in-app Translate button is the higher-quality path for those.
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full overflow-hidden flex flex-col">
        {/* MaintenanceGate polls /api/maintenance and renders a full-screen
            overlay when the dev has flipped system_maintenance.enabled=true
            in Supabase. Paths starting with /admin, /login, /api are
            exempt so admins can still unblock the flag while in the
            maintenance window. */}
        <MaintenanceGate>{children}</MaintenanceGate>
      </body>
    </html>
  );
}
